### ISSUE TITLE
How do I programmatically set the value of the select?

### ISSUE THREAD

**Issue by pigszel** [vrg-success/nativejs-select#13]
On my UI I should display a clear button next to every input fields and select boxes. I just wondered that I could set the nativejs-select box's value. I have tried the classic `document.querySelector('#mySelect').value = '';`, but it did not do anything.

Is it a supported method in this package or is it something I should figure out on my own?

**Comment by vrg-success** [comment]
Hi, I added the method special for you in sandbox https://codesandbox.io/s/priceless-kapitsa-38d5h?file=/src/index.js and may be I will add the feature in new version of nativejs-select, tnx for use my libary  :)

**Comment by vrg-success** [comment]
If you want to set some value in js, you can just trigger click:
```js
document.querySelector('.nativejs-select__option:nth-child(3) .nativejs-select__option_btn').click();
```

**Comment by pigszel** [comment]
> If you want to set some value in js, you can just trigger click:
> 
> ```js
> document.querySelector('.nativejs-select__option:nth-child(3) .nativejs-select__option_btn').click();
> ```

Oh gosh, I did not think I can do that, but of course I can :) 
Thank you for the quick response and the perfect solutions, I really appreciate it. 🥇
