### ISSUE TITLE
Automagically submitting form

### ISSUE THREAD

**Issue by pigszel** [vrg-success/nativejs-select#14]
In #8 you fixed one huge part of the automatically submitting form, but I just discovered that this issue still exists. I managed to solved that by adding the `type="button"` attribute to line 85 in `index.ts` to the `button` with the class of `.nativejs-select__placeholder`.

_Before:_
`<button class="nativejs-select__placeholder">`

_After:_
`<button class="nativejs-select__placeholder" type="button">`

Would you be kind and update and maybe release it as v1.0.6?

**Comment by vrg-success** [comment]
Today I will realize thx for issue

**Comment by vrg-success** [comment]
Done
